# Generated by Django 5.2.4 on 2026-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('alarm_code', models.CharField(db_column='ALARM_ID', max_length=50, unique=True)),
                ('alarm_name', models.CharField(db_column='ALARM_NAME', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'alarm',
            },
        ),
    ]
